baseURL = 'http://localhost:1313/'
title = "AutoAvail"
author = "Clyve Gassant, Hemosoo Woo, Natalie Lim, and Prithvi Bale"
copyright = "Team 12, 2025"

# Development-specific baseURL
[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Access-Control-Allow-Origin = "*"

[development]
  baseURL = "http://localhost:1313/"

timeZone = 'America/New_York'

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = "hugo-bootstrap-theme"
# themesdir = "../.."

disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  # comment out unused taxonomies
  # tag = "tags"
  # series = "series"
  # category = "categories"
  # author = "authors"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
#  post = "/post/:title/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"

[params]
  description = "Chrome extension enabling real-time meeting scheduling in Gmail"
  featherIconsPath = "/images/feather/icons/"

# Disable RSS feed generation
disableKinds = ["RSS", "taxonomy", "term"]

# Disable unused output formats
[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
